services:
  discord-bot:
    build: 
      context: ./discord-bot
      dockerfile: Dockerfile
    container_name: discord-bot
    env_file:
      - ./discord-bot/.env
    volumes:
      - ./discord-bot:/app
    restart: unless-stopped

  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - ./telegram-bot/.env
    volumes:
      - ./telegram-bot:/app
    restart: unless-stopped

  webhook:
    build:
      context: ./webhook
      dockerfile: Dockerfile
    container_name: webhook-service
    env_file:
      - ./webhook/.env
    ports:
      - "8000:8000"
    volumes:
      - ./webhook:/app
    restart: unless-stopped