services:
  discord-bot:
    build: 
      context: ./discord-bot
      dockerfile: Dockerfile
    container_name: discord-bot
    env_file:
      - ./discord-bot/.env
    volumes:
      - ./discord-bot:/app
      - ./shared:/app/shared
    restart: unless-stopped

  telegram-bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    network_mode: bridge
    env_file:
      - ./telegram_bot/.env
    volumes:
      - ./telegram_bot:/app
      - ./shared:/app/shared
    restart: unless-stopped

  webhook:
    build:
      context: ./webhook
      dockerfile: Dockerfile
    container_name: webhook-service
    env_file:
      - ./webhook/.env
    ports:
      - "8000:8000"
    volumes:
      - ./webhook:/app
      - ./shared:/app/shared
    working_dir: /app
    restart: unless-stopped

  steam:
    build:
      context: ./steam
      dockerfile: Dockerfile
    container_name: steam-service
    env_file:
      - ./steam/.env
    volumes:
      - ./steam:/app
      - ./shared:/app/shared
    restart: unless-stopped